name: ios
on:
  pull_request:
    branches:
      - main
  workflow_dispatch: {}
  workflow_call: 

env:
  GIT_CLONE_PATH: ${{ github.run_id }}
  
jobs:
# ***** Prepare ***** #
  prepare:
    runs-on: android
    steps:
      - name: Checkout code 👀 👀 👀 
        uses: actions/checkout@v3
        with:
          path: ${{ env.GIT_CLONE_PATH }}
# ***** Build ***** #
  build:
    runs-on: android
    steps:
      - name: build iOS staging app for testing 
        run: echo "build iOS staging app"   
# ***** Test app ***** #
  test_ios_app:
    runs-on: android
    steps:
      - name: build iOS staging app for testing 
        run: echo "build iOS staging app"
