name: Android Native app
on:
  pull_request:
    branches:
      - main
  workflow_dispatch: {}
  workflow_call: 

env:
  GIT_CLONE_PATH: ${{ github.run_id }}
  
jobs: 
# ***** Test app ***** #
  test_android_app:
    runs-on: android
    steps:
      - name: Test Android staging app for testing 
        run: echo "test Android app"
